### PR TITLE
Rewrite keyword researchers to use stemmer instead of creating forms

### PR DESCRIPTION
**Pull request by nataliashitova**
## Summary

This PR can be summarized in the following changelog entry:

* [yoastseo] Changes the way word forms are recognized in the text of a post or page.

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

These steps should be tested on English, German and Dutch texts. A regression test should be executed comparing the old version (e.g., current RC) and this version.
* Create a post, page, custom post, category, tag, custom taxonomy
* Add a text, title, meta description, slug, image with an alt tag
* Choose a focus keyphrase, fill it in. Use different forms of your keyphrase in the text, title, meta description, slug, image with an alt tag
* In `SEO analysis`, check that every assessment that looks at the use of keyphrase returns correct results. Use https://github.com/Yoast/javascript/wiki/Scoring-SEO-analysis in case of doubts. Note that this PR only changes the way keyphrase forms are recognized in the text, but does not fix existing bugs. Therefore, if the result of an assessment is different from your expectations, please check if the same holds for the old version (13.1).

Related keyphrase and synonym functionality was not altered in this PR, so there should be no regression on this side. In order to see, which assessments also take synonyms into consideration, please consult https://github.com/Yoast/javascript/wiki/Scoring-SEO-analysis.
The metadescription templates (SEO > content types) functionality was also not altered in this PR. Please smoke test it.

Additionally, please pay attention at whether performance has changed in re-analysis of a text since 13.1. You can, for example, introduce a change in the text that affects keyphrase analysis (e.g., add another use of keyphrase) and time how long it takes for the analysis to renew.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  * Keyphrase analysis

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [x] I have added unittests to verify the code works as intended

Fixes https://yoast.atlassian.net/browse/LIN-149

### CODE REVIEW

**Comment by sannevndrmeulen** [comment]
The steps of regression testing for SEO analysis that should be executed (https://github.com/Yoast/javascript/wiki/Scoring-SEO-analysis):
1. Pre-conditions: set site to English, use default editor
- [ ] test all SEO assessments for post
- [ ] test all SEO assessments for page
- [ ] test all SEO assessments for category
- [ ] test all SEO assessments for tag
- [ ] test all SEO assessments for custom post (can be Woocommerce product)
- [ ] test all SEO assessments for custom tag
2. Pre-conditions: set site to German, use default editor
- [ ] test all SEO assessments for post
- [ ] test all SEO assessments for page
- [ ] test all SEO assessments for category
- [ ] test all SEO assessments for tag
- [ ] test all SEO assessments for custom post (can be Woocommerce product)
- [ ] test all SEO assessments for custom tag
3. Pre-conditions: set site to Dutch, use default editor
- [ ] test all SEO assessments for post
- [ ] test all SEO assessments for page
- [ ] test all SEO assessments for category
- [ ] test all SEO assessments for tag
- [ ] test all SEO assessments for custom post (can be Woocommerce product)
- [ ] test all SEO assessments for custom tag
4. Pre-conditions: set site to English, use Classic editor
- [ ] execute general regression for SEO assessments for post/category/custom post
5. Pre-conditions: set site to German, use Classic editor
- [ ] execute general regression for SEO assessments for post/category/custom post
6. Pre-conditions: set site to Dutch, use Classic editor
- [ ] execute general regression for SEO assessments for post/category/custom post
7. Execute basic regression for metadescription templates (SEO > content types) (analysis for default metadescription)
8. About performance testing: it is not clear how to test performance change exactly, we do not have any performance baseline for analysis. So please confirm, lingo-team, if it is indeed sufficient to execute what you mention: "You can, for example, introduce a change in the text that affects keyphrase analysis (e.g., add another use of keyphrase) and time how long it takes for the analysis to renew."

**Comment by nataliashitova** [comment]
@sannevndrmeulen 
> So please confirm, lingo-team, if it is indeed sufficient to execute what you mention: "You can, for example, introduce a change in the text that affects keyphrase analysis (e.g., add another use of keyphrase) and time how long it takes for the analysis to renew."
Yes, unless we have a different option, we should do that.

**Comment by sannevndrmeulen** [comment]
While testing **tag** with site set to English I've noticed that there are less Keyphrase-based SEO assessments. While testing **post** I followed these [11 documented steps](https://github.com/Yoast/javascript/wiki/Scoring-SEO-analysis#keyphrase-based-seo-assessments), for **tag** I only get 8 Keyphrase-based SEO assessments: (is this correct?)
1. Keyphrase in introduction
2. Keyphrase distribution
3. Keyphrase length
4. Keyphrase density
5. Keyphrase in meta description
6. Previously used keyphrase
7. Keyphrase in title
8. Keyphrase in slug

**Comment by nataliashitova** [comment]
@sannevndrmeulen 
I understand that you miss Keyphrase in subheadings, Competing links and Keyphrase in image alt tags.
**Keyphrase in subheadings** only applies if there is at least one subheading. Did you have subheadings in your test text?
**Competing links** only returns a result if there is in fact a link that contains keyphrase in its link text. Did you have such a link in your test text?
**Images alt tags* does not check for images if there are no images added or images do not contain an alt tag. Did you have images with alt tags in your test text?

**Comment by sannevndrmeulen** [comment]
@nataliashitova 
Yes, this is the content of my tag:

Schermafbeelding 2020-02-19 om 09 58 42

And when I check the analysis results (with branding as my Focus Keyphrase), 
this is what I see:

Schermafbeelding 2020-02-19 om 09 59 11

I'm checking my testing results against our current version for Premium, but I don't notice any differences. Are these assessments supposed to show for taxonomies? If that's the case, do I need more content to trigger them?

**Comment by nataliashitova** [comment]
@sannevndrmeulen I checked the code - these three assessments are not applied to taxonomies. So, their absence is expected in both 13.1 and this feature branch zip.

**Comment by Djennez** [comment]
@dariaknl @nataliashitova @sannevndrmeulen 

My performance tests were executed as follows:
- Create the 5 test posts and save them as drafts
- install the plugin for testing
[
- Open the first post and add the keyphrase
- remove the keyphrase
[
- start performance testing from the developer tools
- paste the keyphrase
- stop the performance test
- search the performance metrics for the worker that re-analyzes the text
- note the time it took this worker to run
] repeat 5 times
- run 5 times for all 5 posts
] test for other plugin

The tests are heavily influenced by the state of the machine on which the tests are executed. I had to reboot my mac just before finishing, so the last 6 results are faster. I also think that running tests sequentially will somehow populate more browser memory and slow down every following test by a bit. This would mean that, because I tested the stemming version last, those results are influenced by the first batch of tests. This makes this performance test not very trustworthy.

My results **ALL IN MILLISECONDS**:

Premium 13.1:

  | EN_1 | EN_2 | EN_3 | EN_4 | EN_5
-- | -- | -- | -- | -- | --
Run 1 | 233.50 | 161.06 | 185.31 | 160.06 | 179.65
Run 2 | 198.56 | 198.93 | 204.41 | 174.40 | 233.47
Run 3 | 169.35 | 157.66 | 177.56 | 215.34 | 152.24
Run 4 | 144.19 | 202.48 | 237.69 | 157.73 | 207.64
Run 5 | 189.02 | 225.39 | 150.38 | 217.56 | 137.12
Average  | 186.92 | 189.10 | 191.07 | 185.02 | 182.02

Artifact stemming (based on 13.1-RC1, cursive values are after test machine reboot):

  | EN_1 | EN_2 | EN_3 | EN_4 | EN_5
-- | -- | -- | -- | -- | --
Run 1 | 171.46 | 199.43 | 198.11 | 185.98 | *153.20*
Run 2 | 199.50 | 217.43 | 170.72 | 218.31 | *172.09*
Run 3 | 178.81 | 164.65 | 264.10 | 185.84 | *153.90*
Run 4 | 190.72 | 223.53 | 221.88 | 217.98 | *141.78*
Run 5 | 226.53 | 253.27 | 167.89 | 217.23 | *160.21*
Average  | 193.40 | 211.66 | 204.54 | *205.07* | *156.24*

Difference between plugins per text:

EN_1 | EN_2 | EN_3 | EN_4 | EN_5
-- | -- | -- | -- | --
6.48 | 22.56 | 13.47 | 20.05 | -25.79

Average of the differences: **7.35**

With this average in difference it is my conclusion the difference is negligible. Even when I would remove the tests from the 5th text (where the majority of my after-reboot runs are located), the average difference would be 15.64, which I would say is not very impressively slower.

**Comment by nataliashitova** [comment]
Thanks for testing it @Djennez ! 
Variability within text within version seems at least just as high as variability between versions.

**Comment by sannevndrmeulen** [comment]
I'm testing the German assessments and I've noticed something in the **Length of meta description** assessment. At the end it says, `olltest du sie kürzen!`
Correct me if I'm wrong, but I think this should be, `solltest du zie kürzen!`

Schermafbeelding 2020-03-10 om 13 43 55

**Comment by manuelaugustin** [comment]
@sannevndrmeulen Good catch! I've fixed the translation on translate.wordpress.org.

**Pull request merged**
