### PR TITLE
Update styling after UX check

### PR DESCRIPTION
**Pull request by bintzandt**
## Summary

This PR can be summarized in the following changelog entry:
* [@yoast/replacement-variable-editor] Update styling to incorporate the feedback from UX.
* [@yoast/social-metadata-previews] Update styling to incorporate the feedback from UX.

## Relevant technical choices:
* The Collapsibles have not been updated, this will be done in a later revision
* The `Insert Variable` button will be tackled by Rolf in https://github.com/Yoast/javascript/pull/668.

## Test instructions

This PR can be tested by following these steps:
* Only styling changes. Have a look to see if you like them ;)

## UI changes
No UI changes since it is on a feature branch.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [ ] I have added unittests to verify the code works as intended

Fixes Yoast/wordpress-seo#14617

### CODE REVIEW

**Comment by bintzandt** [comment]
Build is failing because the branch is out-of-date with develop.

**Comment by bintzandt** [comment]
Build is failing because the branch is out-of-date with develop.

**Comment by maartenleenders** [comment]
CR 👍

**Comment by maartenleenders** [comment]
Acc 👍

**Pull request merged**
