### PR TITLE
Let prominent words threshold be dependent on the availability of morphology data

### PR DESCRIPTION
**Pull request by johannadevos**
## Summary

This PR can be summarized in the following changelog entry:

* Sets the threshold for words to be recognized as prominent words from 4 to 2, in case a language has no morphology support. This increases the chance that different word forms are saved, leading to better internal linking suggestions for these languages.

## Relevant technical choices:

*

## Test instructions

This PR can be tested by following these steps:

**Test in a language with morphology support**
* In `Settings`, set your site language to one that has morphology support, for example English.
* Open a post (either new or existing).
* Open the `Network` tab in the inspector.
* Add (English) content to the post. 
* In the `Network` tab, see a request starting with `link_suggestions?prominent_words`.
* Click on the request, then `Headers`. Scroll down and see the prominent words. 
* See that the lowest value a prominent word can have, is 4. 
* This may require some fiddling with your content. 
    * Make sure that you have some words/word forms that occur exactly 4 times, and some words/word forms that occur 3 times (the latter ones, you shouldn't see in the request).
    * Make sure that your text isn't too long. Only the 20 prominent words are shown that occur most frequently, so you don't want to have 20 or more words/word forms with 5 or more occurrences.
    * Make sure that your text is at least 100 words, otherwise no prominent words will be generated.

**Test in a language without morphology support**
* In `Settings`, set your site language to one that has morphology support, for example Danish.
* Open a post (either new or existing).
* Open the `Network` tab in the inspector.
* Add (Danish) content to the post. 
* In the `Network` tab, see a request starting with `link_suggestions?prominent_words`.
* Click on the request, then `Headers`. Scroll down and see the prominent words. 
* See that the lowest value a prominent word can have, is 2. 
* This may require some fiddling with your content. 
    * Make sure that you have some words/word forms that occur exactly 2 times, and some words/word forms that occur 1 time (the latter ones, you shouldn't see in the request).
    * Make sure that your text isn't too long. Only the 20 prominent words are shown that occur most frequently, so you don't want to have 20 or more words/word forms with 5 or more occurrences.
    * Make sure that your text is at least 100 words, otherwise no prominent words will be generated.

## Impact check

* This PR affects the following parts of the plugin, which may require extra testing:
  * The calculation of prominent words.

## UI changes
* [ ] This PR changes the UI in the plugin. I have added the 'UI change' label to this PR.

## Quality assurance

* [x] I have tested this code to the best of my abilities
* [x] I have added unittests to verify the code works as intended

Fixes https://yoast.atlassian.net/browse/P2-138

### CODE REVIEW

**Comment by johannadevos** [comment]
Please also give feedback on the changelog entry, I'm not sure whether it should contain the phrase "prominent words", but I also don't know a good alternative at this point.

**Review by hansjovis — APPROVED** [review]
CR: 👍

**Comment by hansjovis** [comment]
> Please also give feedback on the changelog entry, I'm not sure whether it should contain the phrase "prominent words", but I also don't know a good alternative at this point.

Perhaps we can add a line telling the users why we made this change:
> Sets the threshold for words to be recognized as prominent words from 4 to 2, in case a language has no morphology support. This increases the chance that different word forms are saved, leading to better internal linking suggestions for these languages.

**Comment by hansjovis** [comment]
Acceptance test: ✅

**Pull request merged**
